import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import utilStyles from '../styles/utils.module.css';
import Link from 'next/link'
import { getSortedPostsData } from '../lib/posts';
import Footer from '../components/footer';

export async function getStaticProps() {
  const allPostsData = getSortedPostsData();
  return {
    props: {
      allPostsData,
    },
  };
}

export default function Home({ }) {
  return (
    <>
      <div className={styles.container}>
        <Head>
          <title>naneun bie</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.png" />
        </Head>

        <main className={styles.main}>
          <h1 className={styles.title}>
            Welcome to <Link href="posts/blog/hi">Helen's site!</Link>
          </h1>

          <p className={styles.description}>
            I am the one who love to code and sharing.<br></br>
            Hope you enjoy to looking up my personal website.
          </p>

          <div className={utilStyles.profile}>
            <Image
              priority
              src="/images/bie_avatar.jpeg"
              className={utilStyles.borderCircle}
              height={144}
              width={144}
              alt="Helen's"
            />
            <h1 className={utilStyles.heading2Xl}>Helen Febriani</h1>
            <p>Software Engineer</p>
          </div>

          <p className={styles.subTittle}><b>Journey</b> as <a>Software Engineer</a> still too far, but here is mine</p>
          <div className={utilStyles.grid}>
            <a href="https://nextjs.org/docs" className={styles.card}>
              <Image className={styles.icon} src="/icon/favicon.ico" alt="nextjs" width={25} height={25} />
              <h2>Next JS</h2>
              <p>I made this lovely site project with this !</p>
            </a>

            <a href="https://angular.io/" className={styles.card}>
              <Image src="/icon/angular.png" alt="angular" width={25} height={25} />
              <h2>Angular</h2>
              <p>Working in banking corporate for almost 3 years with angular</p>
            </a>

            <a
              href="https://spring.io/projects/spring-boot"
              className={styles.card}
            >
              <Image src="/icon/spring.svg" alt="spring-boot" width={25} height={25} />
              <h2>Spring Boot</h2>
              <p>Love how magic java works. Experience a lot until now with this lovely framework for working as profesional</p>
            </a>

            <a
              href="#"
              className={styles.card}
            >
              <Image src="/icon/golang.png" alt="angular" width={25} height={25} />
              <h2>Golang</h2>
              <p >
                Explore this pretty things
              </p>
            </a>

            <a
              href="#"
              className={styles.card}
            >
              <Image src="/icon/sql.png" alt="angular" width={25} height={25} />
              <h2>SQL Database</h2>
              <p >
                SQL database, with relational database. I've learn a lot as my profesional work
              </p>
            </a>

            <a
              href="#"
              className={styles.card}
            >
              <Image src="/icon/mongodb.png" alt="angular" width={25} height={25} />
              <h2>Mongo Database</h2>
              <p >
                It's non-SQL database. Based object database but so amazing
              </p>
            </a>
          </div>
        </main>

        {/* <section className={`${utilStyles.headingMd} ${utilStyles.padding1px}`}>
          <h2 className={utilStyles.headingLg}>Blog</h2>
          <ul className={utilStyles.list}>
            {allPostsData.map(({ id, date, title }) => (
              <li className={utilStyles.listItem} key={id}>
                {title}
                <br />
                {id}
                <br />
                {date}
              </li>
            ))}
          </ul>
        </section> */}
      </div>
      <Footer></Footer>
    </>
  )
}
